### ISSUE TITLE
mysql: use 8.0

### ISSUE THREAD

**Issue by derekperkins** [bigcapitalhq/bigcapital#126]
MySQL 5.7 goes EOL on October 31, so it'll be much better all around to use 8.0 before too much usage happens. 8.0 has been out for 5 years, so it's not like that's bleeding edge either, and it's much better all around.
https://endoflife.date/mysql

**Comment by abouolia** [comment]
We've migrated the server database to MariaDB v10 for several reasons, know more through this PR. https://github.com/bigcapitalhq/bigcapital/pull/128
