### ISSUE TITLE
Cannot create customer

### ISSUE THREAD

**Issue by bibstha** [bigcapitalhq/bigcapital#129]
Running locally with docker prod.
I can register a new user and create an organization.
When trying to add a customer, I face 2 issues

1. **Some sort of UI validation** fails on the frontend (no backend API call at all).

https://github.com/bigcapitalhq/bigcapital/assets/51671/228cf94a-860f-4a16-9b95-22ba35d9d2e9

Now, I see this for _ALL_ numerical fields like phone, work phone, shipping postal code, shipping phone number etc.

2. **When I do fill out ALL the fields**, the validation somehow fails on the backend.
_uploaded to imgur since screencapture > 10mb_

![Imgur](https://imgur.com/mW575ON)

**Comment by abouolia** [comment]
We've released a version fixes that just you have to upgrade to the latest version and that issue will be fixed. here's a sample steps from docs how to upgrade. https://docs.bigcapital.ly/docs/deployment/docker#upgrading 

_Let me know if you got something else._
