### ISSUE TITLE
Show the customer/vendor balance in the select field on sales and purchases forms.

### ISSUE THREAD

**Issue by abouolia** [bigcapitalhq/bigcapital#208]
Display the customer/vendor balance beside the name in `CustomersSelect` and `VendorsSelect` for better user experience. because many users want to see the customer/vendor balance before even clicking on the select item.

Simply can be done by changing the `labelAccessor` prop from `code` to `balance` since no codes in customers/vendors.

_Note: Blueprint select component supports a way to display text and label (label is a text aligned to right)._

<img width="352" alt="Screenshot 2023-08-14 at 19 22 31" src="https://github.com/bigcapitalhq/bigcapital/assets/2197422/6ba22741-5ff3-4081-a7c1-ee2745ead624">

**Comment by asenawritescode** [comment]
Screenshot links not working.

**Comment by abouolia** [comment]
@asenawritescode fixed it and I wrote more descriptive description, we're looking forward for your contribution. :)

**Comment by asenawritescode** [comment]
> @asenawritescode fixed it and I wrote more descriptive description, thanks for letting me know we're looking forward for your contribution. :)

Unfortunately, I am stuck with the docker build, there is an issue at the migration stage because I cannot access the dB as per the error messages in the front-end.

**Comment by asenawritescode** [comment]
@abouolia  should this issue be closed ?

**Comment by abouolia** [comment]
@asenawritescode Yes, we have done it and merged it.
