### ISSUE TITLE
Add approve/reject buttons on action bar of the estimate details drawer.

### ISSUE THREAD

**Issue by abouolia** [bigcapitalhq/bigcapital#209]
Approve and reject estimate buttons are exist just on context menu of estimates list, should be added even on actions bar when you open a specific estimate details for better experience.

better to add them between the print button and edit estimate button, with avoiding display "mark as approved" button if it was already approved.

<img width="577" alt="Screenshot 2023-08-14 at 19 34 32" src="https://github.com/bigcapitalhq/bigcapital/assets/2197422/c2ef8f28-aeb6-4a94-bb7d-645a3463494d">

Context menu that has approve and reject buttons

<img width="397" alt="Screenshot 2023-08-14 at 19 35 01" src="https://github.com/bigcapitalhq/bigcapital/assets/2197422/8c784d49-47a4-427f-9986-3349f5bd1ffc">

**Comment by asenawritescode** [comment]
Hi there the screenshots links are probably broken.

**Comment by abouolia** [comment]
I'm sorry about fixed it, Linear synced the content but didn't sync the pictures, btw that task is almost done and under reviewing. https://github.com/bigcapitalhq/bigcapital/pull/304, linked it with the PR to everyone know its status.
