### ISSUE TITLE
[BIG-57] typo: bill success message without bill number.

### ISSUE THREAD

**Issue by abouolia** [bigcapitalhq/bigcapital#216]
Show the success message without bill number cause the bill number is optional.

"The bill has been created successfully."

"The bill has been edited successfully."

![image.png](https://uploads.linear.app/4eaa9562-0643-4be7-9208-f032b139e858/7e2bcaac-fea9-49e2-9ac1-67892fedce22/69a370dc-a775-4307-a01f-0b06a4fbfc40?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRlYWE5NTYyLTA2NDMtNGJlNy05MjA4LWYwMzJiMTM5ZTg1OC83ZTJiY2FhYy1mZWE5LTQ5ZTItOWFjMS02Nzg5MmZlZGNlMjIvNjlhMzcwZGMtYTc3NS00MzA3LWEwMWYtMGIwNmE0ZmJmYzQwIiwiaWF0IjoxNjkyMDQyODU1LCJleHAiOjE2OTIxMjkyNTV9.k09FOVr9vGYKMzbLqQpkZ4SXIQw1Dsssz7No0yHsRnk)

![image.png](https://uploads.linear.app/4eaa9562-0643-4be7-9208-f032b139e858/0bfce0dc-35c1-4437-b31d-1f421423fd5e/fbebc535-4849-4708-ad86-a76302a7514f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRlYWE5NTYyLTA2NDMtNGJlNy05MjA4LWYwMzJiMTM5ZTg1OC8wYmZjZTBkYy0zNWMxLTQ0MzctYjMxZC0xZjQyMTQyM2ZkNWUvZmJlYmM1MzUtNDg0OS00NzA4LWFkODYtYTc2MzAyYTc1MTRmIiwiaWF0IjoxNjkyMDQyODU1LCJleHAiOjE2OTIxMjkyNTV9.XnNM6XOgtmCMyLRgn6Y34uY9m_o5TmzrUs8iRGp1pww)

<sub>From [SyncLinear.com](https://synclinear.com) | [BIG-57](https://linear.app/bigcaptial/issue/BIG-57/typo-bill-success-message-without-bill-number)</sub>

**Comment by KalliopiPliogka** [comment]
Hey! I would like to work on it!

**Comment by KalliopiPliogka** [comment]
I think i fixed it! I've created a pull request(https://github.com/bigcapitalhq/bigcapital/pull/219). 
Check it when you have the time.
