### ISSUE TITLE
Something went wrong! Please try again.

### ISSUE THREAD

**Issue by jaxonashton** [bigcapitalhq/bigcapital#236]
I've installed Bigcapital on a clean VM running Debian 11 w/ 

When I go to `http://<IP>`, I get the following error message when completing the form to register for a new account:

![Screenshot at Sep 04 18-45-59](https://github.com/bigcapitalhq/bigcapital/assets/3246415/0ee5c943-ae7d-432a-9f9f-6a8f850e4388)

When I check what docker containers exist with `sudo docker ps` I get:

![Screenshot at Sep 04 18-50-47](https://github.com/bigcapitalhq/bigcapital/assets/3246415/cbb8883d-dd28-4ba0-bc0a-adbc5a5d358e)

Seems there are a few missing. As this is a clean install using the instructions exactly as presented on https://docs.bigcapital.ly/deployment/docker, I'm hoping someone has an idea as to what is going on here.

When I run `sudo docker ps -a | grep bigcapital-database_migration`, nothing returns.

When I run `docker volume rm bigcapital_prod_mysql`, it returns `Error: No such volume: bigcapital_prod_mysql`.

Something else I noticed is when the instructions mention: "Wait for all containers to be in running state, and then point your browser to http://<IP-ADDRESS>:8000/ to access the application," BC doesn't respond on that port (no, my firewall isn't running). The only response I get is on port 80.

**Comment by jaxonashton** [comment]
Tried this on a new VM and the containers do in fact now show, but they keep terminating:

![image](https://github.com/bigcapitalhq/bigcapital/assets/3246415/c3d19d6c-5684-418b-bbd4-7968bf9df0d4)

**Comment by idiosyncric** [comment]
Did you verify that you filled out all the information in the .env file correctly? 
https://docs.bigcapital.ly/deployment/docker  Step 2. has the line I missed several times
> Change all mail variables to configure it with your mail server and the password of databases.

It took me a few attempts to get it all sorted 
I ended up using GMail for the mail server which worked only on port **587** and make sure to use [App Passwords ](https://support.google.com/accounts/answer/185833?hl=en) and if that password has spaces don't for get to put it in "Quotes" in your .env file
MAIL_SECURE=true because it does not specify in documentation what your options are 

Finally removing the mysql container to have it rebuild if you fiddled with it before that was all working like I did.
```
docker compose --file docker-compose.prod.yml down
docker volume rm bigcapital_mysql
docker compose --file docker-compose.prod.yml up -d
```
A quick side note, the `docker volume rm bigcapital_prod_mysql` also caught me up as well, but when you use `docker ps` you will see it has just been renamed `bigcapaital_mysql`

**Comment by ringnutz** [comment]
I am getting the exact same issue on a fresh install, get this in the nginx log
2023/11/16 00:24:08 [error] 14#14: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.YYY, server: , request: "GET /api/auth/meta HTTP/1.1", upstream: "http://172.31.0.7:3000/api/auth/meta", host: "192.168.1.XX", referrer: "http://192.168.1.XX/auth/login"

**Comment by elbeicktalat** [comment]
Hello everyone,
 I'm facing the same issue, all docker images are running correctly except `database-migration`.  Also I'm not sure that the .env attributes are set correctly.
 
`database-migration log`

```
2024-01-14 13:01:50 wait-for-it.sh: waiting 15 seconds for mysql:3306
2024-01-14 13:01:58 wait-for-it.sh: mysql:3306 is available after 8 seconds
'. See 'commands --help'.: unknown command 'system:migrate:latest
: not found13:01:59 /start.sh: line 3: 
2024-01-14 13:01:59 wait-for-it.sh: waiting 15 seconds for mysql:3306
2024-01-14 13:01:59 wait-for-it.sh: mysql:3306 is available after 0 seconds
2024-01-14 13:01:59 Error: ER_NO_SUCH_TABLE: Table 'bigcapital_system.TENANTS' doesn't exist
2024-01-14 13:01:59     at Sequence._packetToError (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
2024-01-14 13:01:59     at Query.ErrorPacket (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
2024-01-14 13:01:59     at Protocol._parsePacket (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
2024-01-14 13:01:59     at Parser._parsePacket (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
2024-01-14 13:01:59     at Parser.write (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
2024-01-14 13:01:59     at Protocol.write (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
2024-01-14 13:01:59     at Socket.<anonymous> (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
2024-01-14 13:01:59     at Socket.<anonymous> (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
2024-01-14 13:01:59     at Socket.emit (node:events:513:28)
2024-01-14 13:01:59     at addChunk (node:internal/streams/readable:324:12)
2024-01-14 13:01:59     --------------------
2024-01-14 13:01:59     at Protocol._enqueue (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2024-01-14 13:01:59     at Connection.query (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
2024-01-14 13:01:59     at /app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/dialects/mysql/index.js:132:18
2024-01-14 13:01:59     at new Promise (<anonymous>)
2024-01-14 13:01:59     at Client_MySQL._query (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/dialects/mysql/index.js:126:12)
2024-01-14 13:01:59     at executeQuery (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
2024-01-14 13:01:59     at Client_MySQL.query (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/client.js:144:12)
2024-01-14 13:01:59     at Runner.query (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/runner.js:130:36)
2024-01-14 13:01:59     at ensureConnectionCallback (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
2024-01-14 13:01:59     at Runner.ensureConnection (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/runner.js:272:20)
```

Also you can check my `.env` file below:

```
# Mail
MAIL_HOST=smpt.gmail.com
MAIL_USERNAME=example@gmail.com
MAIL_PASSWORD="my password"
MAIL_PORT=587
MAIL_SECURE=true
MAIL_FROM_NAME=admin
MAIL_FROM_ADDRESS=example@gmail.com

# Database
DB_HOST=localhost
DB_USER=bigcapital
DB_PASSWORD=bigcapital
DB_ROOT_PASSWORD=root
DB_CHARSET=utf8

# System database
SYSTEM_DB_NAME=bigcapital_system
# SYSTEM_DB_USER=
# SYSTEM_DB_PASSWORD=
# SYSTEM_DB_NAME=
# SYSTEM_DB_CHARSET=

# Tenant databases
TENANT_DB_NAME_PERFIX=bigcapital_tenant_
# TENANT_DB_HOST=
# TENANT_DB_USER=
# TENANT_DB_PASSWORD=
# TENANT_DB_CHARSET=

# Application
BASE_URL=http://example.com
JWT_SECRET=b0JDZW56RnV6aEthb0RGPXVEcUI

# Jobs MongoDB
MONGODB_DATABASE_URL=mongodb://localhost/bigcapital

# App proxy
PUBLIC_PROXY_PORT=80
PUBLIC_PROXY_SSL_PORT=443

# Agendash
AGENDASH_AUTH_USER=agendash
AGENDASH_AUTH_PASSWORD=123123

# Sign-up restrictions
SIGNUP_DISABLED=false
SIGNUP_ALLOWED_DOMAINS=
SIGNUP_ALLOWED_EMAILS=

# API rate limit (points,duration,block duration).
API_RATE_LIMIT=120,60,600

# Gotenberg API for PDF printing - (production).
GOTENBERG_URL=http://gotenberg:3000
GOTENBERG_DOCS_URL=http://server:3000/public/

# Gotenberg API - (development)
# GOTENBERG_URL=http://gotenberg:3000
# GOTENBERG_DOCS_URL=http://server:3000/public/
```

Running logs
```
PS C:\src\bigcapital> docker compose --file docker-compose.prod.yml up -d
[+] Running 10/10
 ✔ Network bigcapital_default               Created                                                                0.0s
 ✔ Volume "bigcapital_prod_mysql"           Created                                                                0.0s
 ✔ Container bigcapital-redis               Started                                                                0.1s
 ✔ Container bigcapital-webapp              Started                                                                0.1s
 ✔ Container bigcapital-mysql               Started                                                                0.1s
 ✔ Container bigcapital-gotenberg-1         Started                                                                0.1s
 ✔ Container bigcapital-mongo               Started                                                                0.1s
 ✔ Container bigcapital-database-migration  Started                                                                0.1s
 ✔ Container bigcapital-server              Started                                                                0.1s
 ✔ Container bigcapital-nginx-gateway       Started                                                                0.0s
PS C:\src\bigcapital>
```

```
PS C:\src\bigcapital> docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS                                      NAMES
911796a8a077   bigcapital-nginx                     "/bin/sh -c nginx"       10 minutes ago   Up 9 minutes    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   bigcapital-nginx-gateway
fb46a6ada475   ghcr.io/bigcapitalhq/server:latest   "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   3000/tcp                                   bigcapital-server
93c2ba550b1e   bigcapital-mysql                     "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   3306/tcp                                   bigcapital-mysql
dedeff17e158   ghcr.io/bigcapitalhq/webapp:latest   "/docker-entrypoint.…"   10 minutes ago   Up 10 minutes   80/tcp                                     bigcapital-webapp
f8a4cab6d050   bigcapital-mongo                     "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   27017/tcp                                  bigcapital-mongo
3cc44cd37367   bigcapital-redis                     "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   6379/tcp                                   bigcapital-redis
b9fe93ef4df8   gotenberg/gotenberg:7                "/usr/bin/tini -- go…"   10 minutes ago   Up 10 minutes   3000/tcp, 9000/tcp                         bigcapital-gotenberg-1
PS C:\src\bigcapital>
```

**Comment by asenawritescode** [comment]
I have a similar issue : X


> Hello everyone, I'm facing the same issue, all docker images are running correctly except `database-migration`. Also I'm not sure that the .env attributes are set correctly.
> 
> `database-migration log`
> 
> ```
> 2024-01-14 13:01:50 wait-for-it.sh: waiting 15 seconds for mysql:3306
> 2024-01-14 13:01:58 wait-for-it.sh: mysql:3306 is available after 8 seconds
> '. See 'commands --help'.: unknown command 'system:migrate:latest
> : not found13:01:59 /start.sh: line 3: 
> 2024-01-14 13:01:59 wait-for-it.sh: waiting 15 seconds for mysql:3306
> 2024-01-14 13:01:59 wait-for-it.sh: mysql:3306 is available after 0 seconds
> 2024-01-14 13:01:59 Error: ER_NO_SUCH_TABLE: Table 'bigcapital_system.TENANTS' doesn't exist
> 2024-01-14 13:01:59     at Sequence._packetToError (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
> 2024-01-14 13:01:59     at Query.ErrorPacket (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
> 2024-01-14 13:01:59     at Protocol._parsePacket (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
> 2024-01-14 13:01:59     at Parser._parsePacket (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
> 2024-01-14 13:01:59     at Parser.write (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
> 2024-01-14 13:01:59     at Protocol.write (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
> 2024-01-14 13:01:59     at Socket.<anonymous> (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
> 2024-01-14 13:01:59     at Socket.<anonymous> (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
> 2024-01-14 13:01:59     at Socket.emit (node:events:513:28)
> 2024-01-14 13:01:59     at addChunk (node:internal/streams/readable:324:12)
> 2024-01-14 13:01:59     --------------------
> 2024-01-14 13:01:59     at Protocol._enqueue (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
> 2024-01-14 13:01:59     at Connection.query (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
> 2024-01-14 13:01:59     at /app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/dialects/mysql/index.js:132:18
> 2024-01-14 13:01:59     at new Promise (<anonymous>)
> 2024-01-14 13:01:59     at Client_MySQL._query (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/dialects/mysql/index.js:126:12)
> 2024-01-14 13:01:59     at executeQuery (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
> 2024-01-14 13:01:59     at Client_MySQL.query (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/client.js:144:12)
> 2024-01-14 13:01:59     at Runner.query (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/runner.js:130:36)
> 2024-01-14 13:01:59     at ensureConnectionCallback (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
> 2024-01-14 13:01:59     at Runner.ensureConnection (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/runner.js:272:20)
> ```
> 
> Also you can check my `.env` file below:
> 
> ```
> # Mail
> MAIL_HOST=smpt.gmail.com
> MAIL_USERNAME=example@gmail.com
> MAIL_PASSWORD="my password"
> MAIL_PORT=587
> MAIL_SECURE=true
> MAIL_FROM_NAME=admin
> MAIL_FROM_ADDRESS=example@gmail.com
> 
> # Database
> DB_HOST=localhost
> DB_USER=bigcapital
> DB_PASSWORD=bigcapital
> DB_ROOT_PASSWORD=root
> DB_CHARSET=utf8
> 
> # System database
> SYSTEM_DB_NAME=bigcapital_system
> # SYSTEM_DB_USER=
> # SYSTEM_DB_PASSWORD=
> # SYSTEM_DB_NAME=
> # SYSTEM_DB_CHARSET=
> 
> # Tenant databases
> TENANT_DB_NAME_PERFIX=bigcapital_tenant_
> # TENANT_DB_HOST=
> # TENANT_DB_USER=
> # TENANT_DB_PASSWORD=
> # TENANT_DB_CHARSET=
> 
> # Application
> BASE_URL=http://example.com
> JWT_SECRET=b0JDZW56RnV6aEthb0RGPXVEcUI
> 
> # Jobs MongoDB
> MONGODB_DATABASE_URL=mongodb://localhost/bigcapital
> 
> # App proxy
> PUBLIC_PROXY_PORT=80
> PUBLIC_PROXY_SSL_PORT=443
> 
> # Agendash
> AGENDASH_AUTH_USER=agendash
> AGENDASH_AUTH_PASSWORD=123123
> 
> # Sign-up restrictions
> SIGNUP_DISABLED=false
> SIGNUP_ALLOWED_DOMAINS=
> SIGNUP_ALLOWED_EMAILS=
> 
> # API rate limit (points,duration,block duration).
> API_RATE_LIMIT=120,60,600
> 
> # Gotenberg API for PDF printing - (production).
> GOTENBERG_URL=http://gotenberg:3000
> GOTENBERG_DOCS_URL=http://server:3000/public/
> 
> # Gotenberg API - (development)
> # GOTENBERG_URL=http://gotenberg:3000
> # GOTENBERG_DOCS_URL=http://server:3000/public/
> ```
> 
> Running logs
> 
> ```
> PS C:\src\bigcapital> docker compose --file docker-compose.prod.yml up -d
> [+] Running 10/10
>  ✔ Network bigcapital_default               Created                                                                0.0s
>  ✔ Volume "bigcapital_prod_mysql"           Created                                                                0.0s
>  ✔ Container bigcapital-redis               Started                                                                0.1s
>  ✔ Container bigcapital-webapp              Started                                                                0.1s
>  ✔ Container bigcapital-mysql               Started                                                                0.1s
>  ✔ Container bigcapital-gotenberg-1         Started                                                                0.1s
>  ✔ Container bigcapital-mongo               Started                                                                0.1s
>  ✔ Container bigcapital-database-migration  Started                                                                0.1s
>  ✔ Container bigcapital-server              Started                                                                0.1s
>  ✔ Container bigcapital-nginx-gateway       Started                                                                0.0s
> PS C:\src\bigcapital>
> ```
> 
> ```
> PS C:\src\bigcapital> docker ps
> CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS                                      NAMES
> 911796a8a077   bigcapital-nginx                     "/bin/sh -c nginx"       10 minutes ago   Up 9 minutes    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   bigcapital-nginx-gateway
> fb46a6ada475   ghcr.io/bigcapitalhq/server:latest   "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   3000/tcp                                   bigcapital-server
> 93c2ba550b1e   bigcapital-mysql                     "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   3306/tcp                                   bigcapital-mysql
> dedeff17e158   ghcr.io/bigcapitalhq/webapp:latest   "/docker-entrypoint.…"   10 minutes ago   Up 10 minutes   80/tcp                                     bigcapital-webapp
> f8a4cab6d050   bigcapital-mongo                     "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   27017/tcp                                  bigcapital-mongo
> 3cc44cd37367   bigcapital-redis                     "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   6379/tcp                                   bigcapital-redis
> b9fe93ef4df8   gotenberg/gotenberg:7                "/usr/bin/tini -- go…"   10 minutes ago   Up 10 minutes   3000/tcp, 9000/tcp                         bigcapital-gotenberg-1
> PS C:\src\bigcapital>
> ```

**Comment by elbeicktalat** [comment]
@asenawritescode If you have a similar issue try to explain it, Except if it's the exact same issue.

**Comment by elbeicktalat** [comment]
Anyway the server and frontend are running correctly, the issue is with the migration.

<img width="1278" alt="Screenshot 2024-01-14 161330" src="https://github.com/bigcapitalhq/bigcapital/assets/59793332/b6e273c9-fec2-425c-a244-dae8d7462058">

**Comment by asenawritescode** [comment]
> @asenawritescode If you have a similar issue try to explain it, Except if it's the exact same issue.

It is exactly the same problem, works on local though.

**Comment by elbeicktalat** [comment]
@abouolia Can you take a look on this issue, whatever info you need I more than happy to answer you.

I can already tell you that we did follow the installation steps you asked about in this comment:
https://github.com/bigcapitalhq/bigcapital/issues/264#issuecomment-1749370706

Thank you!

**Comment by abouolia** [comment]
@asenawritescode @elbeicktalat What the operating system and CPU architecture do you use? I want to duplicate the same exact environment.

**Comment by abouolia** [comment]
@asenawritescode @elbeicktalat I tried the docker compose setup on Ubuntu, Debian, CentOS and Redhat, I got not problem, I'm afraid you were run it on Windows (that would be my next trial). please let me know what is your OS?

**Comment by asenawritescode** [comment]
I am running docker on windows 10. 

PS.
You also share a different env with all required values preset.

> @asenawritescode @elbeicktalat I tried the docker compose setup on Ubuntu, Debian, CentOS and Redhat, I got no problem, I'm afraid you were run it on Windows (that would be my next trial). please let me know what is your OS?

**Comment by muhammedcrow** [comment]
Hi Fellas I think this issue is windows related as I was having trouble with it until I moved my install to linux debian 12 server and it worked like magic. to confirm this i also tried on Mac OS as will it was also working.

**Comment by elbeicktalat** [comment]
Good coding evryone,

**Comment by elbeicktalat** [comment]
Good coding everyone,
I have solved this issue using docker on wsl ubuntu distribution.

You can install Docker on WSL by following next steps:
1. Go into `https://docs.docker.com/engine/install/ubuntu/` and find the install crul script
2. Go into `https://docs.docker.com/engine/install/linux-postinstall/ ` and follow adding user to docker group
3. Go into `https://docs.docker.com/compose/install/linux/` and install docker compose.

From now on you can follow the bitcapital docs.

**Comment by elbeicktalat** [comment]
Of Course the issue causd by windows.

I'm using:
`Windows 11 - 22H2`
`RYZEN 9 - 5000 SERIES`

**Comment by asenawritescode** [comment]
> Good coding everyone, I have solved this issue using docker on wsl ubuntu distribution.
> 
> You can install Docker on WSL by following next steps:
> 
> 1. Go into `https://docs.docker.com/engine/install/ubuntu/` and find the install crul script
> 2. Go into `https://docs.docker.com/engine/install/linux-postinstall/ ` and follow adding user to docker group
> 3. Go into `https://docs.docker.com/compose/install/linux/` and install docker compose.
> 
> From now on you can follow the bitcapital docs.

Everyone here who has an issue is using windows

**Comment by bigsk1** [comment]
> Hello everyone, I'm facing the same issue, all docker images are running correctly except `database-migration`. Also I'm not sure that the .env attributes are set correctly.
> 
> `database-migration log`
> 
> ```
> 2024-01-14 13:01:50 wait-for-it.sh: waiting 15 seconds for mysql:3306
> 2024-01-14 13:01:58 wait-for-it.sh: mysql:3306 is available after 8 seconds
> '. See 'commands --help'.: unknown command 'system:migrate:latest
> : not found13:01:59 /start.sh: line 3: 
> 2024-01-14 13:01:59 wait-for-it.sh: waiting 15 seconds for mysql:3306
> 2024-01-14 13:01:59 wait-for-it.sh: mysql:3306 is available after 0 seconds
> 2024-01-14 13:01:59 Error: ER_NO_SUCH_TABLE: Table 'bigcapital_system.TENANTS' doesn't exist
> 2024-01-14 13:01:59     at Sequence._packetToError (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
> 2024-01-14 13:01:59     at Query.ErrorPacket (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
> 2024-01-14 13:01:59     at Protocol._parsePacket (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
> 2024-01-14 13:01:59     at Parser._parsePacket (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
> 2024-01-14 13:01:59     at Parser.write (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
> 2024-01-14 13:01:59     at Protocol.write (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
> 2024-01-14 13:01:59     at Socket.<anonymous> (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
> 2024-01-14 13:01:59     at Socket.<anonymous> (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
> 2024-01-14 13:01:59     at Socket.emit (node:events:513:28)
> 2024-01-14 13:01:59     at addChunk (node:internal/streams/readable:324:12)
> 2024-01-14 13:01:59     --------------------
> 2024-01-14 13:01:59     at Protocol._enqueue (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
> 2024-01-14 13:01:59     at Connection.query (/app/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
> 2024-01-14 13:01:59     at /app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/dialects/mysql/index.js:132:18
> 2024-01-14 13:01:59     at new Promise (<anonymous>)
> 2024-01-14 13:01:59     at Client_MySQL._query (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/dialects/mysql/index.js:126:12)
> 2024-01-14 13:01:59     at executeQuery (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
> 2024-01-14 13:01:59     at Client_MySQL.query (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/client.js:144:12)
> 2024-01-14 13:01:59     at Runner.query (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/runner.js:130:36)
> 2024-01-14 13:01:59     at ensureConnectionCallback (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
> 2024-01-14 13:01:59     at Runner.ensureConnection (/app/node_modules/.pnpm/knex@0.95.15_mysql2@1.7.0_mysql@2.18.1/node_modules/knex/lib/execution/runner.js:272:20)
> ```
> 
> Also you can check my `.env` file below:
> 
> ```
> # Mail
> MAIL_HOST=smpt.gmail.com
> MAIL_USERNAME=example@gmail.com
> MAIL_PASSWORD="my password"
> MAIL_PORT=587
> MAIL_SECURE=true
> MAIL_FROM_NAME=admin
> MAIL_FROM_ADDRESS=example@gmail.com
> 
> # Database
> DB_HOST=localhost
> DB_USER=bigcapital
> DB_PASSWORD=bigcapital
> DB_ROOT_PASSWORD=root
> DB_CHARSET=utf8
> 
> # System database
> SYSTEM_DB_NAME=bigcapital_system
> # SYSTEM_DB_USER=
> # SYSTEM_DB_PASSWORD=
> # SYSTEM_DB_NAME=
> # SYSTEM_DB_CHARSET=
> 
> # Tenant databases
> TENANT_DB_NAME_PERFIX=bigcapital_tenant_
> # TENANT_DB_HOST=
> # TENANT_DB_USER=
> # TENANT_DB_PASSWORD=
> # TENANT_DB_CHARSET=
> 
> # Application
> BASE_URL=http://example.com
> JWT_SECRET=b0JDZW56RnV6aEthb0RGPXVEcUI
> 
> # Jobs MongoDB
> MONGODB_DATABASE_URL=mongodb://localhost/bigcapital
> 
> # App proxy
> PUBLIC_PROXY_PORT=80
> PUBLIC_PROXY_SSL_PORT=443
> 
> # Agendash
> AGENDASH_AUTH_USER=agendash
> AGENDASH_AUTH_PASSWORD=123123
> 
> # Sign-up restrictions
> SIGNUP_DISABLED=false
> SIGNUP_ALLOWED_DOMAINS=
> SIGNUP_ALLOWED_EMAILS=
> 
> # API rate limit (points,duration,block duration).
> API_RATE_LIMIT=120,60,600
> 
> # Gotenberg API for PDF printing - (production).
> GOTENBERG_URL=http://gotenberg:3000
> GOTENBERG_DOCS_URL=http://server:3000/public/
> 
> # Gotenberg API - (development)
> # GOTENBERG_URL=http://gotenberg:3000
> # GOTENBERG_DOCS_URL=http://server:3000/public/
> ```
> 
> Running logs
> 
> ```
> PS C:\src\bigcapital> docker compose --file docker-compose.prod.yml up -d
> [+] Running 10/10
>  ✔ Network bigcapital_default               Created                                                                0.0s
>  ✔ Volume "bigcapital_prod_mysql"           Created                                                                0.0s
>  ✔ Container bigcapital-redis               Started                                                                0.1s
>  ✔ Container bigcapital-webapp              Started                                                                0.1s
>  ✔ Container bigcapital-mysql               Started                                                                0.1s
>  ✔ Container bigcapital-gotenberg-1         Started                                                                0.1s
>  ✔ Container bigcapital-mongo               Started                                                                0.1s
>  ✔ Container bigcapital-database-migration  Started                                                                0.1s
>  ✔ Container bigcapital-server              Started                                                                0.1s
>  ✔ Container bigcapital-nginx-gateway       Started                                                                0.0s
> PS C:\src\bigcapital>
> ```
> 
> ```
> PS C:\src\bigcapital> docker ps
> CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS                                      NAMES
> 911796a8a077   bigcapital-nginx                     "/bin/sh -c nginx"       10 minutes ago   Up 9 minutes    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   bigcapital-nginx-gateway
> fb46a6ada475   ghcr.io/bigcapitalhq/server:latest   "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   3000/tcp                                   bigcapital-server
> 93c2ba550b1e   bigcapital-mysql                     "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   3306/tcp                                   bigcapital-mysql
> dedeff17e158   ghcr.io/bigcapitalhq/webapp:latest   "/docker-entrypoint.…"   10 minutes ago   Up 10 minutes   80/tcp                                     bigcapital-webapp
> f8a4cab6d050   bigcapital-mongo                     "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   27017/tcp                                  bigcapital-mongo
> 3cc44cd37367   bigcapital-redis                     "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes   6379/tcp                                   bigcapital-redis
> b9fe93ef4df8   gotenberg/gotenberg:7                "/usr/bin/tini -- go…"   10 minutes ago   Up 10 minutes   3000/tcp, 9000/tcp                         bigcapital-gotenberg-1
> PS C:\src\bigcapital>
> ```

the issue is your mail config, should be smtp not smpt  :)

**Comment by abouolia** [comment]
The issue has been fixed. https://github.com/bigcapitalhq/bigcapital/pull/432
