### ISSUE TITLE
Where we can add project in post in journal entry?

### ISSUE THREAD

**Issue by skanel** [bigcapitalhq/bigcapital#263]

**Comment by abouolia** [comment]
Your question is not obvious, please elaborate more in the description.

**Comment by skanel** [comment]
<img width="1388" alt="Screenshot 2023-10-06 at 9 48 23 AM" src="https://github.com/bigcapitalhq/bigcapital/assets/8022270/8018a128-fd19-4ec6-b51b-cf7743801456">
