### ISSUE TITLE
Current version won't finish docker-compose-prod database migration on Windows 10.

### ISSUE THREAD

**Issue by mm86133** [bigcapitalhq/bigcapital#275]
bigcapital-database-migration  |     at Socket.<anonymous> (/app/packages/server/node_modules/mysql/lib/Connection.js:526:10)
bigcapital-database-migration  |     at Socket.emit (events.js:400:28)
bigcapital-database-migration  |     at addChunk (internal/streams/readable.js:293:12)
bigcapital-database-migration  |     --------------------
bigcapital-database-migration  |     at Protocol._enqueue (/app/packages/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
bigcapital-database-migration  |     at Connection.query (/app/packages/server/node_modules/mysql/lib/Connection.js:198:25)
bigcapital-database-migration  |     at /app/packages/server/node_modules/knex/lib/dialects/mysql/index.js:132:18
bigcapital-database-migration  |     at new Promise (<anonymous>)
bigcapital-database-migration  |     at Client_MySQL._query (/app/packages/server/node_modules/knex/lib/dialects/mysql/index.js:126:12)
bigcapital-database-migration  |     at executeQuery (/app/packages/server/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
bigcapital-database-migration  |     at Client_MySQL.query (/app/packages/server/node_modules/knex/lib/client.js:144:12)
bigcapital-database-migration  |     at Runner.query (/app/packages/server/node_modules/knex/lib/execution/runner.js:130:36)
bigcapital-database-migration  |     at ensureConnectionCallback (/app/packages/server/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
bigcapital-database-migration  |     at Runner.ensureConnection (/app/packages/server/node_modules/knex/lib/execution/runner.js:272:20)
bigcapital-mysql               | 2023-10-24 10:21:27 139921143809792 [Warning] Aborted connection 10 to db: 'bigcapital_system' user: 'bigcapital' host: '172.26.0.6' (Got an error reading communication packets

to reproduce download current version and run docker-compose-prod after filling the .env

**Comment by abouolia** [comment]
The issue has been fixed. https://github.com/bigcapitalhq/bigcapital/pull/432
