### ISSUE TITLE
System breaks when I press the print button.

### ISSUE THREAD

**Issue by asenawritescode** [bigcapitalhq/bigcapital#312]
The system breaks when I press the print button.

How to replicate:

1. Create an invoice
2. View the invoice
3. Print the invoice

Screenshots attached below :

![image](https://uploads.linear.app/4eaa9562-0643-4be7-9208-f032b139e858/101c4d91-b757-4b7a-be84-abd9097a922a/85902b9a-f768-4729-9b94-6c253fa1f965?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRlYWE5NTYyLTA2NDMtNGJlNy05MjA4LWYwMzJiMTM5ZTg1OC8xMDFjNGQ5MS1iNzU3LTRiN2EtYmU4NC1hYmQ5MDk3YTkyMmEvODU5MDJiOWEtZjc2OC00NzI5LTliOTQtNmMyNTNmYTFmOTY1IiwiaWF0IjoxNzA1NTc0OTkzLCJleHAiOjMzMjc2MTM0OTkzfQ.0tCAEglrsdYicaN7WaAkRG3GBbLSaYDEWMPpsG4NZZM)

![image](https://uploads.linear.app/4eaa9562-0643-4be7-9208-f032b139e858/ef211ec8-124f-46cc-95c4-fabf18d1e1a9/8af47b47-235a-4dbc-bbb7-0f55dc83971b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRlYWE5NTYyLTA2NDMtNGJlNy05MjA4LWYwMzJiMTM5ZTg1OC9lZjIxMWVjOC0xMjRmLTQ2Y2MtOTVjNC1mYWJmMThkMWUxYTkvOGFmNDdiNDctMjM1YS00ZGJjLWJiYjctMGY1NWRjODM5NzFiIiwiaWF0IjoxNzA1NTc0OTkzLCJleHAiOjMzMjc2MTM0OTkzfQ.CvEBUIjaUn7ihd6mImDhddknmqfkALElFQNC5A2zV0I)

**Comment by abouolia** [comment]
I've fixed it, it was so urgent issue tomorrow we'll release a new version with other hotbugs. thanks for reporting. 🙏

**Comment by abouolia** [comment]
@asenawritescode  Another thing forgot to mention it here, I added the default values of env vars of gotenburg (service responsible for printing) for development and production, you should use the correct values to avoid any errors on both envs. https://github.com/bigcapitalhq/bigcapital/blob/develop/.env.example#L59
