### ISSUE TITLE
Export & Import buttons dont work

### ISSUE THREAD

**Issue by muhammedcrow** [bigcapitalhq/bigcapital#314]
Hello, I have a propblem with export and import buttons, they don’t do anything when you press them in items, accounts chart, invoices and bills, the only thing they do is print out a the posted below in the console.
and sometimes it doesn’t even print that.
if anyone has any informeation about this please let me know. thank you very much.

![Screenshot 2024-01-19 at 10 49 38 AM](https://uploads.linear.app/4eaa9562-0643-4be7-9208-f032b139e858/688bf192-851f-4404-9ade-09e56bf7cbcb/30183add-6d52-4bc5-9af7-5f6514cadaae?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRlYWE5NTYyLTA2NDMtNGJlNy05MjA4LWYwMzJiMTM5ZTg1OC82ODhiZjE5Mi04NTFmLTQ0MDQtOWFkZS0wOWU1NmJmN2NiY2IvMzAxODNhZGQtNmQ1Mi00YmM1LTlhZjctNWY2NTE0Y2FkYWFlIiwiaWF0IjoxNzA1Njg0NDMwLCJleHAiOjMzMjc2MjQ0NDMwfQ.ufGyDuBrGXxlWOGLRFPTDzKTOyqgPr9-btJHIfn3Zo4 "=1253x")

**Comment by xprnio** [comment]
It looks like importing/exporting data isn't implemented yet in most (?) of the places outside financial statements. However looking at the recent PRs, it seems that even for those the exporting was merged quite recently (with the first one being merged on the 28th of November and the last one on the 19th of January, so two days ago), so general data import/export might be on the roadmap as well.

**Comment by elbeicktalat** [comment]
Also print button doesn't work.

**Comment by abouolia** [comment]
Now the import and export work and print would be functional in the next major release.
