### ISSUE TITLE
[BUG] Expense Details - Amount should not be rounded

### ISSUE THREAD

**Issue by xprnio** [bigcapitalhq/bigcapital#320]
When opening the details pane of an expense, the amount is rounded.
This seems to solely be a webapp issue as the amount is correct when received through the API.

![image](https://uploads.linear.app/4eaa9562-0643-4be7-9208-f032b139e858/4a9095f2-745b-4c3c-867e-7160cf045fa6/f4af66f0-3659-462b-a2b7-1df4f7997e27?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRlYWE5NTYyLTA2NDMtNGJlNy05MjA4LWYwMzJiMTM5ZTg1OC80YTkwOTVmMi03NDViLTRjM2MtODY3ZS03MTYwY2YwNDVmYTYvZjRhZjY2ZjAtMzY1OS00NjJiLWEyYjctMWRmNGY3OTk3ZTI3IiwiaWF0IjoxNzA1Nzc4MDQ1LCJleHAiOjMzMjc2MzM4MDQ1fQ.cTvlWGF09apy04MQxuKcs949i8nZLVtuEgWRs2WKjWc)

**Comment by xprnio** [comment]
@abouolia do you want this or can I have it? I should be done with going through my accounting backlog for the day soon and can pick this one up as it _seems_ like an easy fix.

**Comment by abouolia** [comment]
@xprnio Yeah sure that would be great if you opened a PR, tomorrow in all cases I want to review some open PRs (one of them your PR) and then we'll release a new minor release with some urgent hotfixes.

**Comment by xprnio** [comment]
@abouolia Great, I was just making sure so we wouldn't work on it together lol. I'll have the PR on your table by tomorrow

**Comment by asenawritescode** [comment]
@xprnio 
You can look into #331 also probably the same kind of error.
