### ISSUE TITLE
Amount decimals are set to zero when creating an `New Payment Receive`

### ISSUE THREAD

**Issue by gitmp01** [bigcapitalhq/bigcapital#331]
Steps to reproduce:
1. Payment Receives Lists
2. New payment receive
3. Set required fields
4. Set amount with decimals (1.11 or 0.11)
6. See the new created payment or error

**Comment by gitmp01** [comment]
Looks like a rounding/flooring problem when inserting the amount

**Comment by asenawritescode** [comment]
Hi @xprnio 

Would you like to take this up ?

**Comment by xprnio** [comment]
> Hi @xprnio
> 
> Would you like to take this up ?

Hey yeah, sorry I was away for a bit. Sure thing, I'll have a look at it later today

**Comment by gitmp01** [comment]
Do you have any update on this by chance? I can still see the problem on `v0.14.0`

**Comment by abouolia** [comment]
@gitmp01 Technical entering decimal figure to the backend has no problem, just the problem in displaying the subtotal of the payment and invoice due amount are rounded when you display the payment receive details, it has been fixed.
