### ISSUE TITLE
Can't delete expense

### ISSUE THREAD

**Issue by gitmp01** [bigcapitalhq/bigcapital#345]
#### Create an expense

1. Expenses List
2. New Expense
3. Save & Publish

#### Delete it

1. Expenses List
2. Right mouse button on the created expense
3. Delete
4. Error: Something went wrong!

#### Relevant logs

```
[ERROR] InnoDB: Column last_update in table `mysql`.`innodb_table_stats` is BINARY(4) NOT NULL but should be INT UNSIGNED NOT NULL (flags mismatch)
```

#### Version

`v0.14.0`

**Comment by abouolia** [comment]
It works perfectly from my side, try to compose down and up docker containers and try again might be another problem unrelated to the expenses.
