### ISSUE TITLE
Running on linux VM - Mongo not starting - MongoDB 5.0+ requires a CPU with AVX support

### ISSUE THREAD

**Issue by bjornmonnens** [bigcapitalhq/bigcapital#364]
The docker compose is working as expected. However because my host itself is a VM, I get following ERRORS:

WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

This results in the mongo container not running. Can you maybe build the mongo image from version 4 -> mongo:4.4.18 (https://stackoverflow.com/questions/70818543/mongo-db-deployment-not-working-in-kubernetes-because-processor-doesnt-have-avx)

The error i receive in the frontend is the same as #236  , so that might be related ...

**Comment by bigsk1** [comment]
Use "Host" as cpu type, just ran into this and fixed in proxmox

**Comment by Zebble** [comment]
Can also select "x86-64-v3" or "x86-64-v4" as CPU type, as both of these add AVX:

[https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels](url)

**Comment by Mohamed-sobhi95** [comment]
can we use another type of database that doesn't request AVX
