### ISSUE TITLE
Import, Export, Print Not working

### ISSUE THREAD

**Issue by zafar-2020** [bigcapitalhq/bigcapital#387]
Hello,

Thanks for this software. Looks like stable and feature rich product.

I have installed using the preferred method of Docker installation. The setup was painless and got it up and running quite quickly. However, some of the features  I need to get the software up and running. The import, export buttons are pressing but nothing comes up. Same goes for printing. I followed instructions from here: https://docs.bigcapital.ly/deployment/docker

Is there something specific I need to do to make it working? I do see there are some issues in tracker about issue with import. Is that fixed now?

Also would be great to allow user to upload the receipt for expenses.

Also wondering why there is no tax option for expenses? Sometimes you would have general expense like office equipment that is not linked to any vendor but tax applies and need to be paid to govt.

Looking forward to the responses and become active user of this product.

**Comment by jessydm** [comment]
Did u check if Gotenberg docker container is running ?? It is used for pdf generation.
