### ISSUE TITLE
Get items api throwing Sort column not found.

### ISSUE THREAD

**Issue by er-santosh** [bigcapitalhq/bigcapital#397]
@abouolia 

When i try to visit the items or invoice list page where get items api is implemented, its throwing **Sort column not found.**

This is the api being called while visiting those pages and error of 400 is thrown.
`http://localhost:4000/api/items?page_size=20&page=1&stringified_filter_roles=[]&inactive_mode=false` 

How do i resolve this issue? Or may be any maintainer could help fix this issue.

**Comment by abouolia** [comment]
I think this is just on development, if it was on development I have a major PR will fix that. let me know which environment you are in.

**Comment by abouolia** [comment]
The issue has been fixed.
