### ISSUE TITLE
bigcapital.ly web site is down

### ISSUE THREAD

**Issue by patanne** [bigcapitalhq/bigcapital#403]
Cloudflare is issuing a SSL 525 warning

![image](https://github.com/bigcapitalhq/bigcapital/assets/17474951/a91388dd-c7d1-4272-873e-300a4f187ea5)

**Comment by abouolia** [comment]
Thanks for let us know, the problem sounds from the ssl we'll fix it asap.

**Comment by abouolia** [comment]
The issue has been fixed, thanks again 👍🏼
