### ISSUE TITLE
Bug: Plaid sync imports deposits as withdrawals

### ISSUE THREAD

**Issue by jesucarr** [bigcapitalhq/bigcapital#443]
I just set up a Plaid sync and it imports the deposits as withdrawals. 

Apart from this bug, we should be able to edit or remove imported transactions to be able to fix any possible errors.

**Comment by jesucarr** [comment]
I'm in prod.

**Comment by abouolia** [comment]
Wow great, I got the bug from where, I will push the fix asap.

**Comment by abouolia** [comment]
I've fixed it, we'll ship it in the next major release. https://github.com/bigcapitalhq/bigcapital/pull/481
