### ISSUE TITLE
In general ledger, opening balance does not seem to take in account manual journals

### ISSUE THREAD

**Issue by tranx** [bigcapitalhq/bigcapital#463]
We have explicitly defined a manual journal to move the P&L from previous years to the "Retained earnings" accounts - so the balance of the "other income" at the beginning of the year is 0.

![image](https://github.com/bigcapitalhq/bigcapital/assets/184606/b013afd1-aa6a-4f60-9836-04d8229adac5)

However when asking for balance it seems that the income account starts at the previous year balance, without taking in account the journal entry. 

![image](https://github.com/bigcapitalhq/bigcapital/assets/184606/299a58b4-5e5e-41de-b057-b23314069f43)

Also, in general ledger, in addition to filtering by account (which is currently not working but I believe you are aware about the gap), it would be nice when we sort transaction by date to see the cumulative balance going the same way rather to see stuck by by transaction type/creation date as it is currently. 
This is not critical as other report seem essentially correct - but it would help with clarity.

Finally, as a side note, it would be useful to have a tool to assist with end-of-year process and maintaining and moving P&L accounts balance to retained earnings account.

**Comment by abouolia** [comment]
I was able to duplicate the issue after did the same scenario from my side, you're right thanks for reporting that. but after quick investigation the problem with mines figures the function of closing balance that responsible calculating the balance does look at the mines figures (I will fix this issue in next major release after day or two days).

Some points to move them to issues later.
- Closing balance in general ledger report does not sum the negative figures.
- Filter by account in general ledger does not work.
- Transactions sorting should be by transaction date NOT by the transaction type/creation date.
- View or window to make closing the income and expense accounts more easier.

**Comment by abouolia** [comment]
https://linear.app/bigcaptial/issue/BIG-185/filter-by-account-in-general-ledger-does-not-work

**Comment by tranx** [comment]
That's great ! thanks - we'll update and have a look soon. I imagine that you have seen the new issue I raised over the week-end: BIG-197; This will be the most critical one for us now. Otherwise, we'll do our best to keep you updated on things we identify that can be useful to improve big capital as we use it.
