### ISSUE TITLE
Not able to save bill if using custom tax

### ISSUE THREAD

**Issue by rvpcent** [bigcapitalhq/bigcapital#547]
cant save bills if using custom tax (other than 0% default one)

**Comment by rvpcent** [comment]
edit : after some trial, the transaction cant be saved if tax amount  more than 1.000.000.

**Comment by oleynikd** [comment]
Can't reproduce this. I've been able to save a bill with my own VAT tax:
<img width="832" alt="Screenshot 2024-08-01 at 13 00 43" src="https://github.com/user-attachments/assets/876fc993-1b95-4d4f-93db-45181c42287c">

@rvpcent Could you please share more information on how to reproduce this issue?

**Comment by rvpcent** [comment]
@oleynikd try transaction with tax amount more than 1million. your tax only 20 Euro. try transaction 50.000kg, rate 9800/kg with 11% VAT. 
by trial alot of amount transaction, i cant save anything if thax more than 1.000.000, no matter how much my transaction, if tax amount more than 1 mill, transaction cant be saved. if tax amount under 1 million, saving process got no problem

**Comment by oleynikd** [comment]
Confirmed. This is because of DB decimal fields precision. Taxes are `decimal(8,2)` so they can hold values up to 999,999.99. I'll prepare a fix.

**Comment by rvpcent** [comment]
because my country Currency sometimes my VAT amount more than 100,000,000.00, will helps alot if the limit digit covered the amount. thanks

**Comment by oleynikd** [comment]
@abouolia please check the PR #559
