### ISSUE TITLE
Escaped data in text properties is displayed incorrectly

### ISSUE THREAD

**Issue by oleynikd** [bigcapitalhq/bigcapital#550]
Let's take Invoice as an example. I need to give my Invoice a custom number like "INV-00018/2" but as it gets escaped before storing I will get `INV-00018&#x2F;2` in DB.
https://github.com/bigcapitalhq/bigcapital/blob/788150f80d47456c064ee543c3ee6f1ba141d7a3/packages/server/src/api/controllers/Sales/SalesInvoices.ts#L203
And when I open this Invoice in webapp I will also see `INV-00018&#x2F;2`
The same behaviour is with all `.escape`-ed fields.
We have to either skip escaping of those values, or add an unescape transformation before sending the data to webapp.

<img width="465" alt="Screenshot 2024-07-30 at 12 00 45" src="https://github.com/user-attachments/assets/f227573d-d433-4300-a158-ebe1d1d37802">
<img width="516" alt="Screenshot 2024-07-30 at 12 01 53" src="https://github.com/user-attachments/assets/b7fab4b0-d5df-4a53-b1e6-b11a144c0bb8">

**Comment by abouolia** [comment]
Fixed it. Thanks for reporting.
