### ISSUE TITLE
Due Amount on edit page is calculated wrong with "Exclusive of Tax" Invoice mode

### ISSUE THREAD

**Issue by oleynikd** [bigcapitalhq/bigcapital#558]
As you can see on screenshot, I've added a 20% VAT to my item, and selected "Exclusive of Tax". 
<img width="992" alt="Screenshot 2024-08-01 at 12 51 07" src="https://github.com/user-attachments/assets/d9c2aba9-892e-403b-9b01-5f9aaed2c0e9">

The "Total (EUR)" value is correct, but the "Due Amount" both in header and in footer is wrong.
When you save the Invoice it shows the correct amounts in preview page and in PDF:
<img width="685" alt="Screenshot 2024-08-01 at 12 54 07" src="https://github.com/user-attachments/assets/1a5fc1b5-e3e6-426f-8b92-61ae7932d346">

**Comment by mittalsam98** [comment]
Hey can I work on this?

**Comment by abouolia** [comment]
@mittalsam98 feel free to open pull-request then will review it.

**Comment by mittalsam98** [comment]
@abouolia pls review the PR for this

**Comment by abouolia** [comment]
@mittalsam98 Sure I will review just today we're going to do big launch and then will review it and merge it for the next patch release.
