### ISSUE TITLE
400 response when creating an item without specifying optional account fields

### ISSUE THREAD

**Issue by loganbibby** [bigcapitalhq/bigcapital#561]
For example, when creating a service that isn't purchasable, the purchase and inventory accounts should be optional. If you try to leave them blank, you get a 400 response. 

## Reproduction Steps
1. Add a service that isn't purchasable (like in the screenshot).
2. Unable to add due to 400 response.

![image](https://github.com/user-attachments/assets/95be00a9-1520-40b6-860c-16fe8ecc486b)

**Comment by abouolia** [comment]
From the screenshot the Cost of Goods account is deleted from you side, that type of account shouldn't and cannot be deleted because predefined account. did you delete from the DB directly?

**Comment by loganbibby** [comment]
@abouolia I did, actually. Because we have our own set of accounts that we use and I'm developing my own import from Quickbooks since I have so many company files. Deleted them since you can't edit the predefined accounts with the API.

I do have all of the preferred accounts set, so should it pull from there? Is the COGs account hard coded? If I manually select the COGs and inventory accounts and uncheck `I purchase this item from a vendor`, it'll create the account. 

<img width="461" alt="image" src="https://github.com/user-attachments/assets/e9324012-2535-4a07-8b24-9635b4683d4a">
