### ISSUE TITLE
The total of credit and debit not balanced if the amount is decimal

### ISSUE THREAD

**Issue by abouolia** [bigcapitalhq/bigcapital#685]

**Comment by nklmantey** [comment]
@abouolia is this issue still open? if it is, can you provide some more details

**Comment by abouolia** [comment]
No is not fixed @nklmantey

**Comment by nklmantey** [comment]
can you add an image/screenshot showing this error?

**Comment by abouolia** [comment]
It means when creating a new manual journal the total of credit or debit entries are not balanced if the amounts are decimal for instance take a look at this screenshot.

![image](https://github.com/user-attachments/assets/ab4f0b8d-a103-45d7-a286-875ca8b94420)

**Comment by nklmantey** [comment]
Just opened a pr for this bug https://github.com/bigcapitalhq/bigcapital/pull/722 :)

**Comment by abouolia** [comment]
@nklmantey GREAT, I will take a look at it.
