### ISSUE TITLE
Login page says "Forget my password"

### ISSUE THREAD

**Issue by happnatious1** [bigcapitalhq/bigcapital#726]
The login page currently shows "Forget my password" but should either show "Forgot my password" , "Password Reset" or something similar.

**Comment by abouolia** [comment]
@happnatious1 thanks for your attention, feel free to open a PR to change it to "Forgot my password"

**Comment by ibutiti** [comment]
Happy to put up a PR for this

**Comment by abouolia** [comment]
@ibutiti great, let me know to review it.
