### ISSUE TITLE
Uploading attachments are not working

### ISSUE THREAD

**Issue by StefanHolst** [bigcapitalhq/bigcapital#728]
# Affected Versions
26088a71ee82068b7a45ba6ec4d81307a3dfd541 and v0.20.6

# Description of Bug
Uploading attachments to bills or expences fails when checking if the file was succesfully uploaded.

![image](https://github.com/user-attachments/assets/ba77b285-4f8d-47c7-af18-820dfbae6aae)

![image](https://github.com/user-attachments/assets/0c2e2188-a53a-4d43-bd38-9bbb84e5ae5f)

It looks like the commit https://github.com/bigcapitalhq/bigcapital/commit/37fd4a1fdb033a08aae6bf03e73879bcee4df515 to support `feat: Uploading company logo` broke support for uploading other attachments:  `useUploadAttachments` and `useMutation`

https://github.com/bigcapitalhq/bigcapital/blob/v0.20.6/packages/webapp/src/containers/Attachments/UploadAttachmentsPopoverContent.tsx#L76

# Stacktrace

```
UploadAttachmentsPopoverContent.tsx:111 TypeError: Cannot read properties of undefined (reading 'data')
    at Object.onSuccess (UploadAttachmentsPopoverContent.tsx:80:21)
    at mutation.js:92:71
(anonymous) @ mutation.js:106
Promise.catch
t.execute @ mutation.js:102
n.mutate @ mutationObserver.js:83
onChange @ UploadAttachmentsPopoverContent.tsx:111
onDrop @ ImportDropzoneFile.tsx:46
(anonymous) @ index.mjs:470
(anonymous) @ index.mjs:513
Promise.then
(anonymous) @ index.mjs:512
onClick @ ImportDropzoneFile.tsx:77
ke @ react-dom.production.min.js:54
je @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Dr @ react-dom.production.min.js:105
Hr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cc @ react-dom.production.min.js:273
ze @ react-dom.production.min.js:52
Gr @ react-dom.production.min.js:109
$t @ react-dom.production.min.js:74
Wt @ react-dom.production.min.js:73
Show 17 more frames
Show lessUnderstand this errorAI
UploadAttachmentsPopoverContent.tsx:80 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at Object.onSuccess (UploadAttachmentsPopoverContent.tsx:80:21)
    at mutation.js:92:71
```

**Comment by abouolia** [comment]
Has been fixed.

**Comment by flowe14** [comment]
what was the fix for this , i have updated to latest version , cant upload logo or attached files to expenses.
