### ISSUE TITLE
Maybe use AGPL?

### ISSUE THREAD

**Issue by mrdrogdrog** [bigcapitalhq/bigcapital#97]
You changed the license to GPL which is good, but maybe not the best choice for a web application.
If you use the GPL for web apps then other parties are allowed to change the code base of the backend and don't have to republish their changes because the actual user isn't executing the backend code and the party isn't distributing binaries of the changed code. They just run it on their side and use it for communication.

The AGPL license solves this by stating that software that does network communication also needs to be republished.

https://www.gnu.org/licenses/why-affero-gpl.en.html

**Comment by abouolia** [comment]
We've switched to AGPL to protect the application's networks, thanks for bringing this up.
